package io.github.hyuk0816.r2dbc.schema.diff;

public enum SchemaDiffType {
    CREATE_TABLE,
    ADD_COLUMN,
    ADD_INDEX,
    ADD_UNIQUE_KEY,
    ADD_FOREIGN_KEY,
    MODIFY_COLUMN_TYPE,
    NULLABILITY_MISMATCH,
    DEFAULT_MISMATCH,
    COMMENT_MISMATCH,
    PRIMARY_KEY_MISMATCH,
    FOREIGN_KEY_MISMATCH,
    UNIQUE_KEY_MISMATCH,
    INDEX_MISMATCH,
    EXTRA_COLUMN,
    EXTRA_TABLE
}
